### PR TITLE
Add Nextjournal notebooks

### PR DESCRIPTION
**Pull request by SimonDanisch**
Hi,
I took the freedom to add those great Notebooks to Nextjournal!
It has a nice way to publish notebooks and remembers all installed software, so all notebooks "just run" ;) 
If you already have an account, I can also transfer the ownership of those notebooks to you!

Best,
Simon

### CODE REVIEW

**Comment by domoritz** [comment]
That's awesome. Since we will keep updating the curriculum, it would be great to have a single source of truth. Note how the Colab notebook just loads from GitHub. Could Nextjournal support something similar?

Btw, @jheer is in Berlin as well. I'm unfortunately leaving tomorrow.

**Comment by SimonDanisch** [comment]
>Could Nextjournal support something similar?

We've had that feature on the table several times, and it's still high up in our list! Maybe we can get it into our next feature cycle!

>Btw, @jheer is in Berlin as well. 

Oh great, would be nice to meet up :)

**Comment by domoritz** [comment]
Hi @SimonDanisch, I wanted to see whether you now have support for loading notebooks from GitHub. If so, can you update the URLs in this pull request?

**Comment by SimonDanisch** [comment]
@mk, has there been any progress on that?

**Comment by mk** [comment]
@SimonDanisch not yet I’m afraid but planning for @zampino to tackle that in the coming weeks.

**Comment by domoritz** [comment]
Any updates?

**Comment by mk** [comment]
@domoritz yes, thanks for asking! We just launched the first version of https://github.nextjournal.com so you can for example https://github.nextjournal.com/uwdata/visualization-curriculum/blob/master/altair_data_transformation.ipynb should just work now.

We do not yet offer the ability for people to specify dependencies, so https://github.nextjournal.com/uwdata/visualization-curriculum/blob/master/altair_introduction.ipynb will only run when you install the `vega_datasets` package.

We will see that we come up with a quick solution so they run without further installs and get back to you, hopefully in the coming days.

**Comment by domoritz** [comment]
Awesome. Please ping me when this pull request is ready then.

**Pull request closed without merging**
