### PR TITLE
Add selection composition operators

### PR DESCRIPTION
**Pull request by joelostblom**
Altair now supports operators for composing selections https://altair-viz.github.io/user_guide/interactions.html#composing-multiple-selections

### CODE REVIEW

**Comment by joelostblom** [comment]
Maybe should add a sentence or two with the link also in the text?

**Comment by domoritz** [comment]
Nice. Thank you for the pull request.

Could you add a sentence and a link?

**Comment by joelostblom** [comment]
@domoritz Added!

**Comment by domoritz** [comment]
Thank you!

**Pull request merged**
