### PR TITLE
replace rangeStep with `chart.properties(width={"step": rangeStep})`

### PR DESCRIPTION
**Pull request by hamelsmu**
Per the [latest release notes](https://github.com/altair-viz/altair/releases) 

image

The current use of `rangeStep` is causing an error for people trying to run this notebook with the latest version of Altair.   I tried to make the most minimal change possible to the notebook so that the diffs are human-readable.  🙇 Thank you so much for this very useful tutorial.

cc/: @dansbecker

### CODE REVIEW

**Comment by domoritz** [comment]
Thanks for your pr. We should also clarify the instructions and make sure they indicate the Altair version that is expected.

**Comment by hamelsmu** [comment]
@domoritz thanks!  What do you recommend?  Shall I add a requirements.txt to this PR?

**Comment by jheer** [comment]
Thanks for the PR! I plan to work on this in the coming days, including cutting a new branch and release for Altair v3, and updating master (and the README instructions) to use v4. So nothing more to do, just wait a bit!

**Comment by domoritz** [comment]
@jheer to track dependencies, maybe you can include a lockfile in the next version (using e.g. https://python-poetry.org/).

**Pull request merged**
